// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3HhBmwSQVROmJ9YqEV_Xbzjr8SYQbwAM',
    appId: '1:771349358607:web:YOUR_WEB_APP_ID',
    messagingSenderId: '771349358607',
    projectId: 'alertecameroun',
    authDomain: 'alertecameroun.firebaseapp.com',
    storageBucket: 'alertecameroun.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3HhBmwSQVROmJ9YqEV_Xbzjr8SYQbwAM',
    appId: '1:771349358607:android:2aa8212917f5bef0485b7a',
    messagingSenderId: '771349358607',
    projectId: 'alertecameroun',
    storageBucket: 'alertecameroun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSTeXn727M-4zQraXPyGY0Xhnatabwxp4',
    appId: '1:771349358607:ios:2802e65a4e7ee1b8485b7a',
    messagingSenderId: '771349358607',
    projectId: 'alertecameroun',
    storageBucket: 'alertecameroun.firebasestorage.app',
    iosBundleId: 'waves.digital.virgilant',
  );
}
